### ISSUE TITLE
sending param without title

### ISSUE THREAD

**Issue by iceboy1369** [ashkanpower/EasyWebservice#1]
in the my last code with AsyncTask and HttpPost and use HttpEntity is work good.
i want to work with easy library same as yours...
i can not find anything like this:

"         HttpPost httpPost = new HttpPost(url);
==>  httpPost.setEntity(new StringEntity(json));
         HttpResponse httpResponse = httpClient.execute(httpPost);
         HttpEntity httpEntity = httpResponse.getEntity();
"

**Comment by ashkanpower** [comment]
Yeah, the whole idea behind params was to make easy requests, but I ll try to add this feature too.

**Comment by ashkanpower** [comment]
param without title has beed added.
