### ISSUE TITLE
Response type Array of JSON objects

### ISSUE THREAD

**Issue by behelit** [ashkanpower/EasyWebservice#2]
How would I handle a response type that was an array of JSON objects.
In most cases, the JSON does not have a class identifier so I couldn't create a class type.

E.g.:
```
[
   {"businessName":"Business","abnAcn":"123456"},
   {"businessName":"sample businessName","abnAcn":"sample abnAcn"}
]
```

And I can't seem to treat the response as a String then just process it myself

**Comment by behelit** [comment]
Oops, I can simply pass it as a header

**Comment by behelit** [comment]
I was able to work out the problem.
The class had to be publicly accessible for gson to work through the lib or possibly required a base constructor.
Awesome library!

**Comment by ashkanpower** [comment]
It is a pleasure that you find the library useful.
the whole idea behind this library is that you do not need to parse any JSON response.
just using classes and the library tries to convert JSON to the class provided.
Any suggestion would be appreciated.
