### ISSUE TITLE
ERROR: Failed to resolve: com.github.ashkanpower:easywebservice

### ISSUE THREAD

**Issue by behelit** [ashkanpower/EasyWebservice#3]
ERROR: Failed to resolve: com.github.ashkanpower:easywebservice:+

Does this library still exist?

**Comment by ashkanpower** [comment]
yes you need to use latest commit id instead of version number or +.
right now the latest commit id is
implementation 'com.github.ashkanpower:easywebservice:194d2fe9fc'
